### ISSUE TITLE
Potential incorrect handling of sub-delim characters

### ISSUE THREAD

**Issue by Jotschi** [gbevin/urlencoder#2]
According to RFC 3986 (https://tools.ietf.org/html/rfc3986#section-3.3), there are certain [special characters](https://www.rfc-editor.org/rfc/rfc3986#section-3.3:~:text=delims%0A%0A%20%20%20%20%20%20gen%2Ddelims%20%20%3D%20%22%3A%22%20/%20%22/%22%20/%20%22%3F%22%20/%20%22%23%22%20/%20%22%5B%22%20/%20%22%5D%22%20/%20%22%40%22-,sub%2Ddelims,-%3D%20%22!%22%20/%20%22%24%22%20/%20%22%26%22%20/%20%22%27%22%20/%20%22(%22%20/%20%22)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/%20%22*%22%20/%20%22%2B%22%20/%20%22%2C%22%20/%20%22%3B%22%20/%20%22%3D%22%0A%0A%20%20%20The%20purpose%20of) that are not needed to be encoded. Therefore, these characters should not be decoded either in the URL path section. These characters include "!" / "$" / "&" / "'" / "(" / ")"
/ "*" / "+" / "," / ";" / "=" / ":" / "@"

```java
UrlEncoder.encode("! $ & ' ( ) * + , ; =")
// Yields: %21%20%24%20%26%20%27%20%28%20%29%20%2A%20%2B%20%2C%20%3B%20%3D
```

**Comment by gbevin** [comment]
The encoding requirements are different for different parts of the URL, this library focuses on the query parameters which those characters you mention should be encoded as I understand it in RFC-3986. That being said, maybe we need to include support for other URL components also.
